version: "3.8"
services:
  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=restaurant-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=restaurant_service_db
    depends_on:
      - restaurant-db

  order-service:
    build:
      context: ../delivery_Order_Service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=order-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=order_service_db
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - order-db
      - rabbitmq

  delivery-service:
    build:
      context: ../delivery_Driver_Service
      dockerfile: Dockerfile
    container_name: delivery-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=delivery-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=delivery_service_db
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - delivery-db
      - rabbitmq

  payment-service:
    build:
      context: ../delivery_Payment_Service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=payment-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=payment_service_db
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - payment-db
      - rabbitmq

  notification-service:
    build:
      context: ../delivery_notification_service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  restaurant-db:
    image: mongo:latest
    container_name: restaurant-db
    ports:
      - "27021:27017"
    environment:
      - MONGO_INITDB_DATABASE=restaurant_service_db
    volumes:
      - restaurant-data:/data/db

  order-db:
    image: mongo:latest
    container_name: order-db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=order_service_db
    volumes:
      - order-data:/data/db

  delivery-db:
    image: mongo:latest
    container_name: delivery-db
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=delivery_service_db
    volumes:
      - delivery-data:/data/db

  payment-db:
    image: mongo:latest
    container_name: payment-db
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_DATABASE=payment_service_db
    volumes:
      - payment-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  restaurant-data:
  order-data:
  delivery-data:
  payment-data:
